name: easycourse-local

services:
  mysql-master:
    image: mariadb:11.4
    container_name: easy-course-mysql-master
    restart: unless-stopped
    command: --server-id=1 --log-bin --log-basename=mariadb
    environment:
      MARIADB_ROOT_PASSWORD: Lalka123
      MARIADB_DATABASE: easy_course_db
      MARIADB_USER: easy_course_user
      MARIADB_PASSWORD: easy_course_pass
      MARIADB_REPLICATION_USER: repl
      MARIADB_REPLICATION_PASSWORD: repl_password
    ports:
      - "127.0.0.1:13306:3306"
    volumes:
      - mysql_master_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s

  mysql-replica-1:
    image: mariadb:11.4
    container_name: easy-course-mysql-replica-1
    restart: unless-stopped
    command: --server-id=2 --log-basename=mariadb
    environment:
      MARIADB_ROOT_PASSWORD: Lalka123
      MARIADB_MASTER_HOST: mysql-master
      MARIADB_REPLICATION_USER: repl
      MARIADB_REPLICATION_PASSWORD: repl_password
      MARIADB_HEALTHCHECK_GRANTS: REPLICA MONITOR
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_replica_1_data:/var/lib/mysql
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--replication_io", "--replication_sql", "--replication" ]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 90s

  mysql-replica-2:
    image: mariadb:11.4
    container_name: easy-course-mysql-replica-2
    restart: unless-stopped
    command: --server-id=3 --log-basename=mariadb
    environment:
      MARIADB_ROOT_PASSWORD: Lalka123
      MARIADB_MASTER_HOST: mysql-master
      MARIADB_REPLICATION_USER: repl
      MARIADB_REPLICATION_PASSWORD: repl_password
      MARIADB_HEALTHCHECK_GRANTS: REPLICA MONITOR
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
      - mysql_replica_2_data:/var/lib/mysql
    depends_on:
      mysql-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--replication_io", "--replication_sql", "--replication" ]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 90s

  redis-master:
    image: redis:7-alpine
    container_name: easy-course-redis-master
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_master_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  redis-replica-1:
    image: redis:7-alpine
    container_name: easy-course-redis-replica-1
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    volumes:
      - redis_replica_1_data:/data
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli INFO replication | grep -q 'master_link_status:up'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-replica-2:
    image: redis:7-alpine
    container_name: easy-course-redis-replica-2
    restart: unless-stopped
    ports:
      - "127.0.0.1:6381:6379"
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    volumes:
      - redis_replica_2_data:/data
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli INFO replication | grep -q 'master_link_status:up'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka-1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: easy-course-kafka-1
    restart: unless-stopped
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - kafka_data_1:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka-1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:ANONYMOUS
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: BwCTRrGHRmCSGWafEdeDkQ
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      start_period: 120s
      retries: 5

  kafka-2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: easy-course-kafka-2
    restart: unless-stopped
    ports:
      - "127.0.0.1:9094:9094"
    volumes:
      - kafka_data_2:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:29094,PLAINTEXT_HOST://0.0.0.0:9094,CONTROLLER://kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:ANONYMOUS
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: BwCTRrGHRmCSGWafEdeDkQ
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9094 --list
      interval: 10s
      timeout: 5s
      start_period: 120s
      retries: 5

  kafka-3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: easy-course-kafka-3
    restart: unless-stopped
    ports:
      - "127.0.0.1:9096:9096"
    volumes:
      - kafka_data_3:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:29096,PLAINTEXT_HOST://0.0.0.0:9096,CONTROLLER://kafka-3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:29096,PLAINTEXT_HOST://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:ANONYMOUS
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      CLUSTER_ID: BwCTRrGHRmCSGWafEdeDkQ
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9096 --list
      interval: 10s
      timeout: 5s
      start_period: 120s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: easy-course-kafka-ui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8989:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: easycourse-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:29092,kafka-2:29094,kafka-3:29096
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  easy-course-app-1:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: easy-course-app:local
    container_name: easy-course-app-1
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - app/environment.env
    environment:
      SPRING_PROFILES_ACTIVE: mysql-local
      SPRING_DATASOURCE_URL: jdbc:mariadb://mysql-master:3306/easy_course_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lalka123
      REDIS_HOST: redis-master
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29094,kafka-3:29096
      STEPIK_TOKEN_AOP_ENABLED: "true"
      CORS_ALLOWED_ORIGIN_PATTERN: "http://localhost:*,https://*.tuna.am,http://*.tuna.am"
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-master:
        condition: service_healthy
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      kafka-3:
        condition: service_started

  easy-course-app-2:
    image: easy-course-app:local
    container_name: easy-course-app-2
    restart: unless-stopped
    env_file:
      - app/environment.env
    environment:
      SPRING_PROFILES_ACTIVE: mysql-local
      SPRING_DATASOURCE_URL: jdbc:mariadb://mysql-master:3306/easy_course_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lalka123
      REDIS_HOST: redis-master
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29094,kafka-3:29096
      STEPIK_TOKEN_AOP_ENABLED: "true"
      CORS_ALLOWED_ORIGIN_PATTERN: "http://localhost:*,https://*.tuna.am,http://*.tuna.am"
    depends_on:
      mysql-master:
        condition: service_healthy
      redis-master:
        condition: service_healthy
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      kafka-3:
        condition: service_started

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: easy-course-bot:local
    container_name: easy-course-bot
    restart: unless-stopped
    env_file:
      - app/environment.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29094,kafka-3:29096
    ports:
      - "127.0.0.1:8082:8081"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      kafka-3:
        condition: service_started

  nginx-balancer:
    image: nginx:alpine
    container_name: easy-course-nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - easy-course-app-1
      - easy-course-app-2

  loki:
    image: grafana/loki:3.4.2
    container_name: easy-course-loki
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./deploy/observability/loki-config.yml:/etc/loki/config.yml:ro
      - loki_data:/loki
    ports:
      - "127.0.0.1:3100:3100"

  promtail:
    image: grafana/promtail:3.4.2
    container_name: easy-course-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./deploy/observability/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.6.0
    container_name: easy-course-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_SERVER_ROOT_URL: ${GRAFANA_ROOT_URL:-http://localhost:3000}
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deploy/observability/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - loki

volumes:
  mysql_master_data:
    external: true
    name: app_mysql_master_data
  mysql_replica_1_data:
    external: true
    name: app_mysql_replica_1_data
  mysql_replica_2_data:
    external: true
    name: app_mysql_replica_2_data
  redis_master_data:
    external: true
    name: app_redis_master_data
  redis_replica_1_data:
    external: true
    name: app_redis_replica_1_data
  redis_replica_2_data:
    external: true
    name: app_redis_replica_2_data
  kafka_data_1:
  kafka_data_2:
  kafka_data_3:
  loki_data:
  grafana_data:
